Avoid cython problems with ord
Some versions of cython blow up here with:

  File "rdma/ibverbs.pyx", line 1362, in rdma.ibverbs.QP.modify (rdma/ibverbs.c:22773)
    to_ah_attr(&cattr.ah_attr, attr.ah_attr)
  File "rdma/ibverbs.pyx", line 122, in rdma.ibverbs.to_ah_attr (rdma/ibverbs.c:3533)
    cattr.grh.dgid.raw[i] = ord(attr.DGID[i]);
OverflowError: value too large to convert to char

Because they do a signededness test on the char, even though that makes
no sense.

Just access the string directly.